name: heart
description: 'Extension methods for Strings and Lists, inspired by Haskell'
version: 0.2.0
homepage: 'https://github.com/MadSimple/heart/'

environment:
  sdk: '>=3.0.0 <4.0.0'
#  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.0


dev_dependencies:
  #  flutter_test:
  #    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.6

