name: heart
description: 'Extension methods for Strings and Lists, inspired by Haskell'
version: 0.5.3
homepage: 'https://github.com/MadSimple/heart/'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  collection:

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.6

